### ISSUE TITLE
Unclickable Button

### ISSUE THREAD

**Issue by yuwen41200** [t6847kimo/nctuplus#1]
In `https://plus.nctu.edu.tw/user/`, the `x` button on the right-hand side of the string `開始使用...` is invalid. Clicking on the `x` button has no effect. Besides, at the bottom of every web page, the string `Copy Right` should be `Copyright`. I think it is a typo.
b.t.w. It is better to include the license with the source codes, so that others can know whether this is an FLOSS project or not. Thanks.

**Comment by u9510606** [comment]
Thanks for the suggestions. We have fixed those issues :)
